### ISSUE TITLE
I can't create object of PokeApi..

### ISSUE THREAD

**Issue by csfragsta** [gallexme/pokemongo-api#20]
When i run the following piece of code, I get the following error:

`const Poke = new PokeAPI(options);
             ^

TypeError: PokeAPI is not a constructor
    at Object.<anonymous> (F:\Discord\mybot\pogo.js:17:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3`

Can someone pls assist me with this issue? I am new to PokeApi..if this is not the correct api to use currently, then pls point me to correct API.

**Comment by st0ffern** [comment]
did you import the lib?

`import PokeAPI from 'pokemongo-api'`

**Comment by csfragsta** [comment]
Yes I did:

`const PokeAPI = require('pokemongo-api');`

**Comment by st0ffern** [comment]
You may need to change that to:

`const PokeAPI = require('pokemongo-api').default;`

**Comment by csfragsta** [comment]
Thanks, Now it works but is unable to login. Say's the following. What might be the issue?

`[!] Endpoint missing in request, lets try again.. in 5 seconds`

**Comment by st0ffern** [comment]
well this repo is outdated, and i do not maintain it 😞

**Comment by csfragsta** [comment]
Lol you could have said me that earlier...that's sad though...Can you point me to a working repo?

**Comment by st0ffern** [comment]
nope 🤣

**Comment by csfragsta** [comment]
Any working repo you can guide me to ;(

**Comment by csfragsta** [comment]
[i] Received PTC access token!
[i] Login cache saved to file!
[!] Endpoint missing in request, lets try again.. in 5 seconds
[!] Endpoint missing in request, lets try again.. in 5 seconds
[!] Endpoint missing in request, lets try again.. in 5 seconds
[!] Endpoint missing in request, lets try again.. in 5 seconds

How can i solve this issue? :(

**Comment by st0ffern** [comment]
crack the newest update
